FROM jenkins/jenkins:lts
#COPY executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy
#ENV JENKINS_OPTS --httpPort=-1 --httpsPort=8083 --httpsCertificate=/var/lib/jenkins/cert --httpsPrivateKey=/var/lib/jenkins/pk
EXPOSE 8084