doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        #config_docker:
        dbname:           app_symfony
        user:             '%env(DATABASE_USER)%'
        password:         root
        host:             '%env(DATABASE_HOST)%'
        port:             '%env(DATABASE_PORT)%'
        server_version:   'mariadb-10.4.12'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
